# Generated by Django 4.2.4 on 2023-09-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0002_book_created_book_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Author name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Author description')),
            ],
        ),
    ]
