# Generated by Django 4.2.4 on 2023-09-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
