# Generated by Django 4.2.4 on 2023-09-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochniki', '0005_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spravochniki.country', verbose_name='Country'),
        ),
    ]
